// import '../src/models/my_user_model.dart';
// import '../src/models/ride.dart';

// class RideDatabase {
//   // Create a list of Ride objects
//   List<Ride> rides = [
//     Ride(
//       user: "1",
//       driver: "3",
//       pickupLocation: "UM Sport Centre",
//       destinationLocation: "UM KK1",
//       distance: 12.0,
//       typeOfRide: "Normal",
//       baseFare: 1.3,
//       totalReceived: 15.6,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:14:06.040351Z"),
//       sharedWithFriends: [
//         MyUser(
//           id: '2',
//           username: "Alex Ng",
//           email: "alexng6432@example.com",
//           password: "123456789",
//           phoneNumber: "0173977641",
//           profilePicture: 'assets/kloop.jpg',
//           friends: [],
//         ),
//         MyUser(
//           id: '3',
//           username: "Iskandar Daniel",
//           email: "isdaniel29_@example.com",
//           password: "123456789",
//           phoneNumber: "0123086404",
//           profilePicture: 'assets/haaland.jpg',
//           friends: [],
//         ),
//       ],
//     ),
//     Ride(
//       user: "1",
//       driver: "3",
//       pickupLocation: "Um KK1",
//       destinationLocation: "Sunway Piramid Mall",
//       distance: 11.3,
//       typeOfRide: "Smooth",
//       baseFare: 1.0,
//       totalReceived: 11.3,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:14:54.989869Z"),
//       sharedWithFriends: [
//         MyUser(
//           id: '3',
//           username: "Iskandar Daniel",
//           email: "isdaniel29_@example.com",
//           password: "123456789",
//           phoneNumber: "0123086404",
//           profilePicture: 'assets/haaland.jpg',
//           friends: [],
//         ),
//       ],
//     ),
//     Ride(
//       user: "1",
//       driver: "3",
//       pickupLocation: "Sunway Piramid Mall",
//       destinationLocation: "UM KK1",
//       distance: 11.3,
//       typeOfRide: "Peak",
//       baseFare: 1.5,
//       totalReceived: 16.95,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:15:26.263922Z"),
//       sharedWithFriends: [
//         MyUser(
//           id: '2',
//           username: "Alex Ng",
//           email: "alexng6432@example.com",
//           password: "123456789",
//           phoneNumber: "0173977641",
//           profilePicture: 'assets/kloop.jpg',
//           friends: [],
//         ),
//         MyUser(
//           id: '4',
//           username: "Vheeshal Parameswaran",
//           email: "vheeshal89@example.com",
//           password: "123456789",
//           phoneNumber: "0128673495",
//           profilePicture: 'assets/ronaldo.jpg',
//           friends: [],
//         ),
//       ],
//     ),
//     Ride(
//       user: "1",
//       driver: "5",
//       pickupLocation: "UM KK1",
//       destinationLocation: "TBS",
//       distance: 21.1,
//       typeOfRide: "Smooth",
//       baseFare: 1.0,
//       totalReceived: 21.1,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:16:14.686419Z"),
//       sharedWithFriends: [
//         MyUser(
//           id: '4',
//           username: "Vheeshal Parameswaran",
//           email: "vheeshal89@example.com",
//           password: "123456789",
//           phoneNumber: "0128673495",
//           profilePicture: 'assets/ronaldo.jpg',
//           friends: [],
//         ),
//       ],
//     ),
//     Ride(
//       user: "1",
//       driver: "1",
//       pickupLocation: "Pavilion Bukit Jalil",
//       destinationLocation: "KL Gateway Residence",
//       distance: 19.4,
//       typeOfRide: "Normal",
//       baseFare: 1.3,
//       totalReceived: 25.21,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:18:47.189728Z"),
//       sharedWithFriends: [],
//     ),
//     Ride(
//       user: "1",
//       driver: "6",
//       pickupLocation: "UM KK1",
//       destinationLocation: "UM KK11",
//       distance: 2.4,
//       typeOfRide: "Normal",
//       baseFare: 1.3,
//       totalReceived: 3.12,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:19:30.138684Z"),
//       sharedWithFriends: [],
//     ),
//     Ride(
//       user: "1",
//       driver: "4",
//       pickupLocation: "UM KK1",
//       destinationLocation: "EcoCheras",
//       distance: 23.4,
//       typeOfRide: "Smooth",
//       baseFare: 1.0,
//       totalReceived: 23.39,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:20:09.556270Z"),
//       sharedWithFriends: [
//         MyUser(
//           id: '2',
//           username: "Alex Ng",
//           email: "alexng6432@example.com",
//           password: "123456789",
//           phoneNumber: "0173977641",
//           profilePicture: 'assets/kloop.jpg',
//           friends: [],
//         ),
//         MyUser(
//           id: '4',
//           username: "Vheeshal Parameswaran",
//           email: "vheeshal89@example.com",
//           password: "123456789",
//           phoneNumber: "0128673495",
//           profilePicture: 'assets/ronaldo.jpg',
//           friends: [],
//         ),
//       ],
//     ),
//     Ride(
//       user: "1",
//       driver: "2",
//       pickupLocation: "Pavilion@Bukit Jalil",
//       destinationLocation: "KL Gateway Residence",
//       distance: 23.9,
//       typeOfRide: "Peak",
//       baseFare: 1.5,
//       totalReceived: 35.84,
//       completed: false,
//       date: DateTime.parse("2024-05-23T16:21:23.329285Z"),
//       sharedWithFriends: [],
//     ),
//   ];
// }
